apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app-python
  template:
    metadata:
      labels:
        app: flask-app-python
    spec:
      containers:
      - name: flask-app-python
        image: nrt.ocir.io/nrcfeuv8jnfa/flask-app-python:latest
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
